name: elogsari_mobile
description: A PBL P2MD Flutter Project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  google_sign_in: ^6.1.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  reusable: ^0.0.2
  form_validator: ^2.1.1
  dio: ^5.4.0
  hyperui: ^0.0.1
  get: ^4.6.6
  image_picker: ^1.0.4
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/opening-page.png
    - assets/images/logo-google.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
